version: '3.9'

services:
  backend:
    build:
      context: ./Backend
    container_name: semblance_backend
    env_file:
      - ./Backend/env/.env.prod
    ports:
      - 8000:8000
  reverseproxy:
    container_name: reverseproxy
    build:
      context: ./reverseproxy
    ports:
      - 80:80
    volumes:
      - ./Backend/static:/static
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf
