version: '3.9'

services:
  frontend:
    image: tieje/frontend:5
    container_name: semblance_frontend
    build:
      context: ./Frontend
    ports:
      - 80:80
  backend:
    image: tieje/backend:3
    build:
      context: ./Backend
    volumes:
      - ./Backend:/backend
    container_name: semblance_backend
    command: gunicorn config.wsgi
    env_file:
      - ./Backend/env/.env.prod
    ports:
      - 8000:8000
