version: '3.9'

services:
#  backend:
#    build: ./Backend
#    image: tieje/backend:latest
#    container_name: prod-backend
#    command: gunicorn config.wsgi
#    # Sets the service's environment variables. Use '.env.prod' for production:
#    env_file:
#      - ./Backend/env/.env.prod
#    # Volumes are mounted, meaning any changes made on the host machine will be reflected in the containers which mount the volume
#    # [source]:[target] Meaning, that the backend folder in the container is bind mounted to the backend directory
#    ports:
#      - 8000:8000
  frontend:
    image: tieje/frontend:latest
    command: serve -l 5001 -s build
    ports:
      - 5001:5001
  # for when the time comes.
  # the book says we need a volume within the db service and a volume outside of the db service...
      # it's totally possible to just create a new volume every time, but it's simple extension of code to make it so that the volume is available to multiple services.
      # For example, what if we wanted another container that backs up the data of the volume?
      # https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference
  nginx:
    image: tieje/nginx:latest
    ports:
      - "80:80"
