# Objective: to simulate backend and frontend containers locally with localhosts for the frontend and backend without
#  - nginx
#  - gunicorn

version: '3.9'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile-dev
    container_name: semblance_backend_dev
    env_file:
      - ./Backend/env/.env.prod
    ports:
      - 8000:8000
    volumes:
      - ./Backend/:/backend
  frontend:
    container_name: semblance_frontend_dev
    build:
      context: ./Frontend
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    volumes:
      - ./Frontend/:/frontend
