version: '3.9'

services:
  backend:
    image: tieje/backend:10
    build:
      context: ./Backend
    container_name: semblance_backend
    env_file:
      - ./Backend/env/.env.prod
    networks:
      - semblance-net
  frontend:
    image: tieje/frontend:11
    container_name: semblance_frontend
    build:
      context: ./frontend
    ports:
      - 80:80
    networks:
      - semblance-net
    volumes:
      - ./Backend/static:/static
networks:
  semblance-net:
    driver: overlay
