version: '3.9'

services:
  backend:
    image: tieje/backend:8
    build:
      context: ./Backend
    container_name: semblance_backend
    env_file:
      - ./Backend/env/.env.prod
    ports:
      - 8000:8000
    networks:
      - semblance-net
  frontend:
    image: tieje/frontend:8
    container_name: semblance_frontend
    build:
      context: ./frontend
    ports:
      - 80:80
    networks:
      - semblance-net
networks:
  semblance-net:
    driver: overlay
