version: '3.9'

services:
  backend:
    build:
      context: ./Backend
    container_name: semblance_backend
    env_file:
      - ./Backend/env/.env.prod
    ports:
      - 8000:8000
  frontend:
    container_name: semblance_frontend
    build:
      context: ./frontend
    ports:
      - 80:80
    volumes:
      - ./Backend/static:/static
      - ./Frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./Frontend/build/:/usr/share/nginx/html
